export const countries = [
  { code: "LB", name: "لبنان" },
  { code: "SY", name: "سوريا" },
  { code: "TR", name: "تركيا" },
  { code: "IQ", name: "العراق" },
];

export const citiesByCountry: Record<string, string[]> = {
  LB: [
    "بيروت",
    "طرابلس",
    "صيدا",
    "صور",
    "زحلة",
    "جبيل",
    "جونية",
    "بعلبك",
    "النبطية",
    "عاليه",
    "بنت جبيل",
    "الهرمل",
  ],
  SY: [
    "دمشق",
    "ريف دمشق",
    "حلب",
    "حمص",
    "حماة",
    "اللاذقية",
    "طرطوس",
    "إدلب",
    "درعا",
    "السويداء",
    "القنيطرة",
    "دير الزور",
    "الرقة",
    "الحسكة",
  ],
  TR: [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Mersin",
    "İstanbul",
    "İzmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Kahramanmaraş",
    "Mardin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "Kırıkkale",
    "Batman",
    "Şırnak",
    "Bartın",
    "Ardahan",
    "Iğdır",
    "Yalova",
    "Karabük",
    "Kilis",
    "Osmaniye",
    "Düzce",
  ],
  IQ: [
    "بغداد",
    "البصرة",
    "الموصل",
    "أربيل",
    "السليمانية",
    "دهوك",
    "النجف",
    "كربلاء",
    "الأنبار",
    "كركوك",
    "ديالى",
    "بابل",
    "واسط",
    "ذي قار",
    "ميسان",
    "القادسية",
    "صلاح الدين",
    "نينوى",
  ],
};
